# filename: create_corpus.py | Code Generated by Sidekick is for learning and experimentation purposes only.
from csv import DictWriter
from pathlib import Path


ROOT = Path.cwd()
DOCUMENTS = ROOT / "data" / "documents"
DOCUMENTS.mkdir(parents=True, exist_ok=True)


documents = {
    "security_policy.txt": """
NORTHSTAR ANALYTICS — INFORMATION SECURITY POLICY
Document status: Synthetic test data
Effective date: January 1, 2024
Review date: December 31, 2025
Policy owner: Maya Chen, Director of Security Operations

PURPOSE
This policy defines the minimum information-security requirements for Northstar Analytics,
a fictional company. It applies to Engineering, Sales, Customer Success, and Operations.

ACCESS MANAGEMENT
All workforce members must use company-managed accounts and multifactor authentication.
Access reviews must be completed quarterly. The target is 100% completion within 10 business
days of each quarter-end. Departing personnel must have access removed within four hours
of confirmed departure notification.

DATA CLASSIFICATION
Company data is classified as Public, Internal, Confidential, or Restricted. Customer
contracts, credentials, employee records, and production data are Restricted. Restricted
data may be accessed only by authorized personnel with a documented business need.

SECURITY INCIDENTS
Suspected security incidents must be reported to Security Operations immediately. Critical
incidents require acknowledgement within 30 minutes, containment within four hours when
practicable, and a documented post-incident review within 10 business days.

ENGINEERING CONTROLS
Production changes require approved code review, automated testing, and deployment logging.
Secrets must not be stored in source code. Vulnerability findings rated Critical or High
must have an owner and remediation plan within two business days.

TRAINING AND EVIDENCE
Security training is required annually, with a target completion rate of at least 98%.
Evidence includes access-review records, training reports, incident records, and deployment
logs. Maya Chen is responsible for policy monitoring and quarterly reporting.
""",

    "code_review_process.txt": """
NORTHSTAR ANALYTICS — CODE REVIEW PROCESS
Document status: Synthetic test data
Effective date: January 1, 2024
Process owner: Rafael Ortiz, Engineering Manager

PURPOSE
This process governs how Engineering reviews application and infrastructure changes before
they are deployed to production.

STANDARD WORKFLOW
1. The developer creates a branch and links the change to a work item.
2. The developer adds automated tests and completes the pull-request checklist.
3. A qualified reviewer evaluates logic, security, maintainability, and test coverage.
4. The pull request receives required approvals before merging.
5. The deployment pipeline records the merge, test result, reviewer, and deployment time.

APPROVAL THRESHOLDS
Routine changes require one qualified approval. Changes affecting authentication,
authorization, Restricted data, payment logic, or production infrastructure require two
qualified approvals, including one reviewer with relevant subject-matter expertise.

QUALITY TARGETS
At least 95% of production-bound pull requests should include a linked work item.
At least 90% should include automated test evidence. Emergency changes require retrospective
review within one business day.

REJECTION AND ESCALATION
Reviewers must request changes when security controls, tests, documentation, or acceptance
criteria are incomplete. A developer may escalate an unresolved review to Rafael Ortiz.
The target review turnaround is one business day for routine changes and four business hours
for urgent production fixes.

EVIDENCE
Required evidence includes the pull request, approvals, automated test results, exceptions,
and deployment record. Rafael Ortiz reviews monthly compliance metrics and reports material
exceptions to Maya Chen.
""",

    "customer_complaints_policy.txt": """
NORTHSTAR ANALYTICS — CUSTOMER COMPLAINTS POLICY
Document status: Synthetic test data
Effective date: January 1, 2024
Policy owner: Priya Nair, Director of Customer Success

PURPOSE
This policy defines how Northstar Analytics receives, records, investigates, resolves, and
escalates customer complaints for Core Platform and Analytics Pro.

DEFINITIONS
A complaint is an expression of dissatisfaction that requires investigation or corrective
action. A complaint is distinct from a standard support request, although a support request
may become a complaint if service expectations are not met.

REQUIRED RESPONSE TIMES
Customer Success must acknowledge a complaint within one business day. The target is to
resolve standard complaints within five business days. Complaints involving security,
privacy, billing, or potential contractual impact must be escalated to the appropriate
functional owner on the same business day.

WORKFLOW
1. Record the customer, product, region, issue category, priority, and received date.
2. Assign an owner and acknowledge the complaint.
3. Investigate the cause using support history and customer context.
4. Provide a documented response and corrective action.
5. Obtain customer confirmation when appropriate and close the record.
6. Review trends monthly for systemic improvements.

QUALITY THRESHOLDS
At least 95% of complaints should receive acknowledgement within one business day.
At least 90% of standard complaints should be resolved within five business days.
Complaints reopened by the customer require a manager review within two business days.

MEASUREMENT
The business_metrics.csv file contains support_cases, resolved_cases, and
average_resolution_days. These fields support trend analysis but do not replace individual
complaint records. Priya Nair owns monthly reporting and corrective-action tracking.
""",

    "employee_satisfaction_policy.txt": """
NORTHSTAR ANALYTICS — EMPLOYEE SATISFACTION POLICY
Document status: Synthetic test data
Effective date: January 1, 2024
Policy owner: Elena Brooks, Director of People Operations

MEASUREMENT
Employee satisfaction is measured on a 0–100 scale through a quarterly anonymous survey.
The score is the average of valid responses across Engineering, Sales, Customer Success,
and Operations. The company target is at least 78.

GOVERNANCE
People Operations administers the survey during the final month of each quarter. Results
are segmented by department and reported at company level. Results with fewer than five
responses are suppressed to protect confidentiality.

ACTION THRESHOLDS
A score below 70 requires a documented improvement plan within 30 days. A decline of five
or more points from the prior quarter requires leadership review. Improvement plans should
address workload, manager effectiveness, career development, tools, or operating processes.

RELEVANT POLICIES
Employee satisfaction may be affected by code-review workload, customer escalation volume,
sales target pressure, training requirements, and access to appropriate work tools. These
relationships are hypotheses for analysis and are not proof of causation.

DATA SOURCE
The business_metrics.csv file contains an employee_satisfaction_score field using the
0–100 scale. The value is synthetic and repeated across operational rows for analytical
testing. Elena Brooks owns survey governance and quarterly action tracking.
""",

    "customer_success_strategy.txt": """
NORTHSTAR ANALYTICS — CUSTOMER SUCCESS STRATEGY
Document status: Synthetic test data
Effective date: January 1, 2024
Strategy owner: Priya Nair, Director of Customer Success

OBJECTIVE
Customer Success supports retention and adoption for Core Platform and Analytics Pro across
North America, Europe, and Asia-Pacific. The strategy applies to Enterprise, Mid-Market,
and SMB customer segments.

CUSTOMER HEALTH
Customer health is assessed using product adoption, support activity, open escalations,
renewal timing, and executive engagement. A declining health signal requires an owner and
next action within five business days.

RETENTION TARGETS
The operating target is to reduce avoidable customer churn while maintaining responsive
service. Monthly churn rate is calculated as churned_customers divided by customers_start.
The business_metrics.csv file contains both fields and customers_end for reconciliation.

SERVICE TARGETS
Customer Success targets acknowledgement of complaints within one business day and standard
resolution within five business days. Support trends should be reviewed with revenue,
customer counts, and segment information rather than in isolation.

RECOMMENDED ACTIONS
For repeated complaints, Customer Success should coordinate a root-cause review with
Engineering. For declining adoption, the account team should provide enablement or a
success plan. For high-risk renewals, Sales and Customer Success should agree on an owner,
next milestone, and customer communication plan.

REPORTING
Priya Nair reviews monthly retention, support, and resolution metrics. The strategy should
be adjusted when a policy creates avoidable customer friction or when service performance
falls below the documented thresholds.
""",

    "sales_performance_policy.txt": """
NORTHSTAR ANALYTICS — SALES PERFORMANCE POLICY
Document status: Synthetic test data
Effective date: January 1, 2024
Policy owner: Marcus Lee, Vice President of Sales

SCOPE
This policy governs sales performance reporting for Core Platform and Analytics Pro across
North America, Europe, and Asia-Pacific. It covers Enterprise, Mid-Market, and SMB segments.

METRICS
Revenue is recorded as a fictional monthly amount in the business_metrics.csv file.
Customers_start, new_customers, churned_customers, and customers_end support customer-base
analysis. The reconciliation formula is customers_end = customers_start + new_customers
- churned_customers.

PERFORMANCE REVIEW
Sales performance is reviewed monthly and summarized quarterly. Regional comparisons should
consider product mix, customer segment, new-customer volume, churn, and customer-success
outcomes. Q4 means October, November, and December.

OPERATING EXPECTATIONS
Sales teams must maintain accurate opportunity and customer records. Material forecast
changes require an explanation. Customer commitments involving product capability, service
levels, or implementation timing must be coordinated with Customer Success and Engineering.

CUSTOMER SUCCESS LINKAGE
Sales performance is not evaluated only on new revenue. Leadership should also review
churned customers, support workload, resolution time, and employee satisfaction. A policy
change should be considered when sales incentives appear to encourage commitments that
increase complaints, support cases, or avoidable churn.

GOVERNANCE
Marcus Lee owns monthly performance reporting. Priya Nair provides customer-success context,
and Elena Brooks provides relevant employee-satisfaction trends.
""",

    "industry_benchmark_reference.txt": """
NORTHSTAR ANALYTICS — SYNTHETIC BENCHMARK REFERENCE
Document status: Synthetic test data
Effective date: January 1, 2024
Owner: Elena Brooks, Director of People Operations

IMPORTANT LIMITATION
All values in this document are synthetic comparison benchmarks created solely for testing
retrieval, quantitative analysis, and recommendation workflows. They are not authoritative
external research, market statistics, or Deloitte guidance.

COMPARISON BENCHMARKS
Employee satisfaction benchmark: 75 on a 0–100 scale.
Monthly customer churn benchmark: 2.5% of customers_start.
Average complaint-resolution benchmark: 5.0 business days.
Support-case resolution benchmark: 90% of cases resolved within the reporting period.

COMPARISON METHOD
Compare Northstar Analytics results with these synthetic values only after confirming the
metric definition, period, population, and denominator. Employee satisfaction should use
employee_satisfaction_score. Churn should use churned_customers divided by
customers_start. Support resolution should use resolved_cases divided by support_cases.
Average resolution should use average_resolution_days.

INTERPRETATION
A result above or below a benchmark is an analytical signal, not proof of a cause. Analysts
must consider region, product, customer segment, reporting period, and data completeness.
Recommendations should be connected to documented company policies and customer-success
strategies.

KNOWN LIMITATIONS
The benchmarks are not validated against external sources. The dataset is fictional, and
the employee satisfaction score is repeated across operational rows for testing convenience.
"""
}


for filename, content in documents.items():
    (DOCUMENTS / filename).write_text(content.strip() + "\n", encoding="utf-8")


fields = [
    "month",
    "quarter",
    "year",
    "region",
    "product",
    "customer_segment",
    "revenue",
    "customers_start",
    "new_customers",
    "churned_customers",
    "customers_end",
    "employee_satisfaction_score",
    "support_cases",
    "resolved_cases",
    "average_resolution_days",
]

regions = ["North America", "Europe", "Asia-Pacific"]
products = ["Core Platform", "Analytics Pro"]
segments = ["Enterprise", "Mid-Market", "SMB"]
months = [
    (2024, month) for month in range(1, 13)
] + [
    (2025, month) for month in range(1, 13)
]

csv_path = ROOT / "data" / "business_metrics.csv"
csv_path.parent.mkdir(parents=True, exist_ok=True)

rows = []

for month_index, (year, month_number) in enumerate(months):
    quarter = f"Q{((month_number - 1) // 3) + 1}"
    month = f"{year}-{month_number:02d}"

    for region_index, region in enumerate(regions):
        for product_index, product in enumerate(products):
            for segment_index, segment in enumerate(segments):
                customers_start = (
                    90
                    + region_index * 18
                    + product_index * 14
                    + segment_index * 25
                    + (month_index * 3)
                )
                new_customers = (
                    8
                    + region_index
                    + product_index * 2
                    + segment_index
                    + (month_index % 4)
                )
                churned_customers = max(
                    1,
                    round(customers_start * (0.018 + segment_index * 0.004)),
                )
                customers_end = (
                    customers_start + new_customers - churned_customers
                )

                revenue = round(
                    (
                        18000
                        + region_index * 3500
                        + product_index * 6500
                        + segment_index * 9000
                    )
                    * (1 + month_index * 0.012)
                )

                satisfaction = min(
                    95,
                    74
                    + region_index
                    + product_index
                    + (month_index // 6)
                    - segment_index,
                )

                support_cases = (
                    28
                    + region_index * 5
                    + product_index * 7
                    + segment_index * 4
                    + (month_index % 5)
                )
                resolved_cases = max(
                    1,
                    round(support_cases * (0.88 + (month_index % 3) * 0.02)),
                )
                average_resolution_days = round(
                    4.8
                    - (month_index % 4) * 0.25
                    + region_index * 0.15
                    + segment_index * 0.2,
                    2,
                )

                rows.append({
                    "month": month,
                    "quarter": quarter,
                    "year": year,
                    "region": region,
                    "product": product,
                    "customer_segment": segment,
                    "revenue": revenue,
                    "customers_start": customers_start,
                    "new_customers": new_customers,
                    "churned_customers": churned_customers,
                    "customers_end": customers_end,
                    "employee_satisfaction_score": satisfaction,
                    "support_cases": support_cases,
                    "resolved_cases": resolved_cases,
                    "average_resolution_days": average_resolution_days,
                })

with csv_path.open("w", newline="", encoding="utf-8") as file:
    writer = DictWriter(file, fieldnames=fields)
    writer.writeheader()
    writer.writerows(rows)

print(f"Created {len(documents)} text documents in {DOCUMENTS}")
print(f"Created {len(rows)} metric rows in {csv_path}")
print("Corpus generation complete.")
